
insert into dbo.orders(ORDER_REF, ORDER_DATE, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, Supplier_ID, Invoice_ID) select s1.ORDER_REF, s1.ORDER_DATE, s1.ORDER_TOTAL_AMOUNT, s1.ORDER_DESCRIPTION, s1.ORDER_STATUS, s1.ORDER_LINE_AMOUNT, s2.Supplier_ID, s3.Invoice_ID from dbo.XXBCM_ORDER_MGT s1
INNER JOIN suppliers s2  ON Supplier_ID = s2.Supplier_ID
INNER JOIN invoices s3 ON Invoice_ID = s3.Invoice_ID

--insert into dbo.orders(ORDER_REF, ORDER_DATE, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, Supplier_ID, Invoice_ID) select s1.ORDER_REF, s1.ORDER_DATE, s1.ORDER_TOTAL_AMOUNT, s1.ORDER_DESCRIPTION, s1.ORDER_STATUS, s1.ORDER_LINE_AMOUNT, s2.Supplier_ID, s3.Invoice_ID from dbo.XXBCM_ORDER_MGT s1, dbo.suppliers s2, dbo.invoices s3
--where s2.SUPPLIER_NAME = s1.SUPPLIER_NAME and s3.INVOICE_REFERENCE = s1.INVOICE_REFERENCE
--INNER JOIN suppliers s2  ON s1.SUPPLIER_NAME = s2.SUPPLIER_NAME
--INNER JOIN invoices s3 ON s1.INVOICE_REFERENCE = s3.INVOICE_REFERENCE

--insert into dbo.orders(ORDER_REF, ORDER_DATE, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT) select ORDER_REF, ORDER_DATE, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT from dbo.XXBCM_ORDER_MGT

--select * from dbo.orders
--Delete from dbo.orders