CREATE TABLE suppliers(
   
   	SUPPLIER_NAME 		VARCHAR(2000), 
	SUPP_CONTACT_NAME 	VARCHAR(2000), 
	SUPP_ADDRESS 		VARCHAR(2000), 
	SUPP_CONTACT_NUMBER VARCHAR(2000), 
	SUPP_EMAIL 			VARCHAR(2000),
	Supplier_ID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	);