CREATE TABLE orders(
   
   ORDER_REF 			VARCHAR(2000), 
	ORDER_DATE 			VARCHAR(2000), 
	ORDER_TOTAL_AMOUNT 	VARCHAR(2000), 
	ORDER_DESCRIPTION 	VARCHAR(2000), 
	ORDER_STATUS 		VARCHAR(2000), 
	ORDER_LINE_AMOUNT 	VARCHAR(2000),
	Supplier_ID INT CONSTRAINT fkSupplier FOREIGN KEY (Supplier_ID) REFERENCES suppliers(Supplier_ID),
	Invoice_ID INT CONSTRAINT fkInvoice FOREIGN KEY (Invoice_ID) REFERENCES invoices(Invoice_ID),
	Order_ID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
);